In [2]:
import numpy as np
import pandas as pd

In [61]:
df = pd.read_csv('../vehicles.csv')
df.head()


df.columns

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

Renaming columns

In [5]:
df = df.rename(columns={'Make':'Manufacturer'})

In [6]:
df.rename(columns={'Manufacturer':'Make','Engine Displacement':'Displacement'}, inplace = True)

In [7]:
df.rename(columns={'Make':'Manufacturer','Displacement':'Engine Displacement'}, inplace = True)

In [8]:
df

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

Filtering data

In [9]:
df[df['Manufacturer'] == 'Ford']

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11440,Ford,Aerostar Van,1986,2.3,4.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,17.347895,18,22,19,467.736842,1750
11441,Ford,Aerostar Van,1986,2.3,4.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,13.733750,23,26,24,370.291667,1400
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950
11443,Ford,Aerostar Van,1986,2.8,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,18.311667,16,22,18,493.722222,1850
11444,Ford,Aerostar Van,1986,3.0,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,17.347895,17,22,19,467.736842,1750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14381,Ford,Windstar FWD Wagon,2000,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950
14382,Ford,Windstar FWD Wagon,2000,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950
14383,Ford,Windstar FWD Wagon,2001,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850
14384,Ford,Windstar FWD Wagon,2002,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,21,18,493.722222,1850
14385,Ford,Windstar FWD Wagon,2003,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850

In [10]:
df_ford = df[df['Manufacturer'] == 'Ford']
df_ford

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11440,Ford,Aerostar Van,1986,2.3,4.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,17.347895,18,22,19,467.736842,1750
11441,Ford,Aerostar Van,1986,2.3,4.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,13.733750,23,26,24,370.291667,1400
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950
11443,Ford,Aerostar Van,1986,2.8,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,18.311667,16,22,18,493.722222,1850
11444,Ford,Aerostar Van,1986,3.0,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,17.347895,17,22,19,467.736842,1750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14381,Ford,Windstar FWD Wagon,2000,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950
14382,Ford,Windstar FWD Wagon,2000,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,19.388824,15,21,17,522.764706,1950
14383,Ford,Windstar FWD Wagon,2001,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850
14384,Ford,Windstar FWD Wagon,2002,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,21,18,493.722222,1850
14385,Ford,Windstar FWD Wagon,2003,3.8,6.0,Automatic 4-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,22,18,493.722222,1850

In [11]:
df_ford_1986 = df[(df['Manufacturer'] == 'Ford') & (df['Year'] == 1986)]
df_ford_1986

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11440,Ford,Aerostar Van,1986,2.3,4.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,17.347895,18,22,19,467.736842,1750
11441,Ford,Aerostar Van,1986,2.3,4.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,13.733750,23,26,24,370.291667,1400
11442,Ford,Aerostar Van,1986,2.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Vans,Regular,19.388824,15,21,17,522.764706,1950
11443,Ford,Aerostar Van,1986,2.8,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,18.311667,16,22,18,493.722222,1850
11444,Ford,Aerostar Van,1986,3.0,6.0,Manual 5-spd,Rear-Wheel Drive,Vans,Regular,17.347895,17,22,19,467.736842,1750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14270,Ford,Thunderbird,1986,2.3,4.0,Automatic 3-spd,Rear-Wheel Drive,Compact Cars,Regular,18.311667,16,20,18,493.722222,1850
14271,Ford,Thunderbird,1986,2.3,4.0,Manual 5-spd,Rear-Wheel Drive,Compact Cars,Regular,16.480500,18,24,20,444.350000,1650
14272,Ford,Thunderbird,1986,3.8,6.0,Automatic 3-spd,Rear-Wheel Drive,Compact Cars,Regular,18.311667,17,21,18,493.722222,1850
14273,Ford,Thunderbird,1986,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Compact Cars,Regular,17.347895,17,24,19,467.736842,1750
14274,Ford,Thunderbird,1986,5.0,8.0,Automatic 4-spd,Rear-Wheel Drive,Compact Cars,Regular,17.347895,16,24,19,467.736842,1750

In [12]:
df.describe()

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952.00000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
mean,2000.71640,3.338493,5.765076,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,10.08529,1.359395,1.755268,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,1984.00000,0.600000,2.000000,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,1991.00000,2.200000,4.000000,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,2001.00000,3.000000,6.000000,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,2010.00000,4.300000,6.000000,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,2017.00000,8.400000,16.000000,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

In [13]:
df['Hello'] = 'Hello'
df.head()

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Hello
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,Hello
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,Hello
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,Hello
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,Hello
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,Hello

In [14]:
from datetime import datetime 
# Current date time in local system print(datetime.now())
df['Age'] = datetime.now().year - df['Year']

In [15]:
df['2020'] = df['Age'] + df['Year']

In [16]:
df

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Hello,Age,2020
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,Hello,36,2020
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,Hello,36,2020
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,Hello,35,2020
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,Hello,35,2020
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,Hello,33,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,Hello,7,2020
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,Hello,6,2020
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,Hello,5,2020
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,Hello,4,2020
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,Hello,4,2020

Drop columns

In [17]:
df.columns

Index(['Manufacturer', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year', 'Hello', 'Age', '2020'],
      dtype='object')

In [18]:
df.drop('2020', axis=1, inplace = True)

In [19]:
df.drop(['Highway MPG','City MPG'], axis=1, inplace = True)

Applying Functions to columns

In [20]:
df['Fuel Barrels/Year'].sum()

633080.763419701

In [21]:
df.sum()

Manufacturer               AM GeneralAM GeneralAM GeneralAM GeneralASC In...
Model                      DJ Po Vehicle 2WDFJ8c Post OfficePost Office D...
Year                                                                71929756
Engine Displacement                                                   120026
Cylinders                                                             207266
Transmission               Automatic 3-spdAutomatic 3-spdAutomatic 3-spdA...
Drivetrain                 2-Wheel Drive2-Wheel DriveRear-Wheel DriveRear...
Vehicle Class              Special Purpose Vehicle 2WDSpecial Purpose Veh...
Fuel Type                  RegularRegularRegularRegularPremiumRegularRegu...
Fuel Barrels/Year                                                     633081
Combined MPG                                                          716499
CO2 Emission Grams/Mile                                          1.70886e+07
Fuel Cost/Year                                                      68042700
Hello                      HelloHelloHelloHelloHelloHelloHelloHelloHelloH...
Age                                                                   693284
dtype: object

In [23]:
maxyear = df['Year'].max()
maxcitympg = df['Combined MPG'].max()
print(f'In {maxyear} there haven\'t been more than {maxcitympg} miles per gallon.')

In 2017 there haven't been more than 56 miles per gallon.

Merging Dataframes

In [26]:
df = df.sort_values(by = ['Year','Combined MPG'], ascending = False)

In [27]:
df.nlargest(3,'Year')

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Hello,Age
33280,Toyota,Prius Eco,2017,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Cars,Regular,5.885893,56,158.0,600,Hello,3
33278,Toyota,Prius,2017,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Cars,Regular,6.338654,52,171.0,650,Hello,3
17058,Honda,Accord Hybrid,2017,2.0,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Cars,Regular,6.866875,48,183.0,700,Hello,3

In [28]:
df = df.sort_index()
df

,Manufacturer,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Hello,Age
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,17,522.764706,1950,Hello,36
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,683.615385,2550,Hello,36
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,555.437500,2100,Hello,35
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,683.615385,2550,Hello,35
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,16,555.437500,2550,Hello,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,36,244.000000,1100,Hello,7
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,36,243.000000,1100,Hello,6
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,36,244.000000,1100,Hello,5
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,36,246.000000,1100,Hello,4
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,35,255.000000,1150,Hello,4

In [30]:
df['Manufacturer'].apply(str.upper)

0              AM GENERAL
1              AM GENERAL
2              AM GENERAL
3              AM GENERAL
4        ASC INCORPORATED
               ...
35947               SMART
35948               SMART
35949               SMART
35950               SMART
35951               SMART
Name: Manufacturer, Length: 35952, dtype: object

In [32]:
a_to_b = lambda x: x.replace('a','b')


df[['Manufacturer','Transmission']].apply(a_to_b)

           Manufacturer     Transmission
0            AM General  Automatic 3-spd
1            AM General  Automatic 3-spd
2            AM General  Automatic 3-spd
3            AM General  Automatic 3-spd
4      ASC Incorporated  Automatic 4-spd
...                 ...              ...
35947             smart        Auto(AM5)
35948             smart        Auto(AM5)
35949             smart        Auto(AM5)
35950             smart        Auto(AM6)
35951             smart     Manual 5-spd

[35952 rows x 2 columns]

In [38]:
uncapitalise = lambda x: x.lower()

df['Manufacturer'].apply(uncapitalise)

0              am general
1              am general
2              am general
3              am general
4        asc incorporated
               ...
35947               smart
35948               smart
35949               smart
35950               smart
35951               smart
Name: Manufacturer, Length: 35952, dtype: object

Dataframe Aggregation using groupby

In [52]:
df.groupby(['Drivetrain','Manufacturer'])['Cylinders'].mean()

Drivetrain        Manufacturer
2-Wheel Drive     AM General               5.000000
                  Buick                    7.333333
                  Chevrolet                6.540000
                  Chrysler                 6.000000
                  Dodge                    6.338028
                                             ...
Rear-Wheel Drive  Vixen Motor Company      6.000000
                  Volkswagen               4.000000
                  Volvo                    4.345946
                  Wallace Environmental    7.870968
                  smart                    3.000000
Name: Cylinders, Length: 298, dtype: float64

In [64]:
df.groupby(['Drivetrain'])[['Cylinders','Fuel Cost/Year']].agg(['mean','min','max'])

                           Cylinders            Fuel Cost/Year
                                mean  min   max           mean   min   max
Drivetrain
2-Wheel Drive               6.156028  4.0   8.0    2115.011820  1150  3700
2-Wheel Drive, Front        4.000000  4.0   4.0    1450.000000  1450  1450
4-Wheel Drive               6.364839  4.0  12.0    1971.644612  1150  3400
4-Wheel or All-Wheel Drive  6.143626  3.0  16.0    2165.023835  1200  4050
All-Wheel Drive             5.980383  3.0  16.0    1863.217263  1000  4050
Front-Wheel Drive           4.608172  3.0   8.0    1503.131708   600  2700
Part-time 4-Wheel Drive     7.113924  4.0  12.0    2131.645570  1650  3700
Rear-Wheel Drive            6.643486  2.0  12.0    2140.397611  1000  5800

In [63]:
df.groupby(['Fuel Type'])[['Cylinders','City MPG']].agg(['mean','min','max'])

                            Cylinders              City MPG
                                 mean  min   max       mean min max
Fuel Type
CNG                          6.500000  4.0   8.0  15.966667   8  27
Diesel                       6.225027  4.0  10.0  21.173436  13  38
Gasoline or E85              6.974059  4.0   8.0  15.347280  10  28
Gasoline or natural gas      6.800000  4.0   8.0  13.700000  10  21
Gasoline or propane          8.000000  8.0   8.0  12.000000  11  13
Midgrade                     7.864865  6.0   8.0  14.851351  13  21
Premium                      6.365286  2.0  16.0  16.793166   6  42
Premium Gas or Electricity   4.235294  2.0   8.0  30.705882  20  41
Premium and Electricity      4.850000  3.0   8.0  24.900000  16  37
Premium or E85               6.892562  4.0  12.0  17.305785  11  24
Regular                      5.420952  2.0  12.0  17.970195   7  58
Regular Gas and Electricity  4.000000  4.0   4.0  43.125000  38  51
Regular Gas or Electricity   4.000000  4.0   4.0  43.000000  43  43